import Head from 'next/head';
const about = () => {
	return (
		<div>
			<Head>
				<title>About || Web Dev News</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="font-bold text-2xl">About </h1>
		</div>
	);
};

export default about;
